name: CI/CD — Shapes Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Expose repo root to PYTHONPATH 
      run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

    - name: Run pytest
      run: pytest -q

  docker-deploy:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-shapes-app .

    - name: Echo deploy ✔️
      run: echo "✅ Docker image built — would be deployed here"